solution
Shubham-Porwall/Sales-Tax pull request #1
Opened 2022-01-24 10:49 UTC by Shubham-Porwall

Creating a pull request for reviewing of sales-tax code

2022-01-24 11:01 UTC, kalpana19sharma requested changes

2022-01-24 11:01 UTC, kalpana19sharma commented on input.rb
> +class Inp
Use proper class and method names.

2022-01-24 11:01 UTC, kalpana19sharma commented on input.rb
> +      @ch
Use proper variable names

2022-01-24 11:01 UTC, kalpana19sharma commented on input.rb
> +          if ( str.split(/ /).first.to_f.negative?() || str.split(/ /).last.to_f.negative?() )
I think it's 4 space indentation.

2022-01-24 11:01 UTC, kalpana19sharma commented on input.rb
> +
Remove extra empty lines. Just add one new line at the end of the file.

2022-01-24 11:01 UTC, kalpana19sharma commented on new_arr.rb
> +      end
Use meaning-full variable, classes, modules, method names. Please fix this in the whole code.

2022-01-24 11:01 UTC, kalpana19sharma commented on new_arr.rb
> +  New_arr = []
Use correct naming convention.

2022-01-24 11:01 UTC, kalpana19sharma commented on tax_determination.rb
> +module Determine
meaning full name

2022-01-25 03:03 UTC, kalpana19sharma requested changes

2022-01-25 03:03 UTC, kalpana19sharma commented on input.rb
> +    @for_quit
Why do we need instance variable here. Local variable should be enough, no?

2022-01-25 03:03 UTC, kalpana19sharma commented on tax_determination.rb
> +module Tax_Determination
https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#naming

2022-01-25 03:03 UTC, kalpana19sharma commented on input.rb
> +      inputs = gets.chomp
why inputs? I mean why plural?

2022-01-25 03:03 UTC, kalpana19sharma commented on input.rb
> +      if ( inputs.split(/ /).first.to_f.negative?() || inputs.split(/ /).last.to_f.negative?() )
1. We can store `inputs.split(/ /)` in a variable.
2. No need to add empty `()` with method call.
```suggestion
      if ( inputs.split(/ /).first.to_f.negative? || inputs.split(/ /).last.to_f.negative? )
```

2022-01-25 03:03 UTC, kalpana19sharma commented on input.rb
> +      end
Fix indentation.

2022-01-25 03:03 UTC, kalpana19sharma commented on main.rb
> +arr = user.read_input
Use a meaning full name instead of `arr`.

2022-01-25 03:03 UTC, kalpana19sharma commented on new_arr.rb
> +    for i in (0...arr.length)
Since we are processing array elements instead of index so you should use `each` loop on array.

2022-01-25 03:03 UTC, kalpana19sharma commented on new_arr.rb
> +
Fix empty line.

2022-01-25 03:03 UTC, kalpana19sharma commented on result.rb
> +    Result::RESULT << arr1
I think local variable should be enough here. No need of constant.

2022-01-25 03:03 UTC, kalpana19sharma commented on sort.rb
> +    for i in (0...arr.length)
Use `each` loop.

2022-01-25 03:03 UTC, kalpana19sharma commented on sort.rb
> +      @last = arr[i].split(/ /).last.to_f
Use local variable. We use instance variables when we need to access the variable across the methods.

2022-01-25 03:03 UTC, kalpana19sharma commented on tax_calculate.rb
> +  def return_all_tax_value
Add an empty line between method definition.

2022-01-25 03:03 UTC, kalpana19sharma commented on tax_determination.rb
> +    @bool = false
Use local variable.

2022-01-25 03:03 UTC, kalpana19sharma commented on tax_determination.rb
> +    end
You can directly return `@bool`.

2022-01-25 03:03 UTC, kalpana19sharma commented on tax_determination.rb
> +    end
Try to find a simpler way to do this in ruby.

2022-01-25 03:03 UTC, kalpana19sharma commented on tax_determination.rb
> +  def isExempt(arr)
Methods that return boolean values should end with `?`. And use `snake_case` for method and variable names. Use meaning full parameter names.
```suggestion
  def is_exempt?(products)
```

2022-01-25 03:03 UTC, kalpana19sharma commented on tax_determination.rb
> +  def isExempt(arr)
I think this method should handle one product at a time since you are calling this method for each product.

2022-01-25 07:17 UTC, Shubham-Porwall commented on input.rb
> +      inputs = gets.chomp
We are taking every string into that local variable and than push into array that's why indicate this as inputs.

2022-01-26 10:14 UTC, kalpana19sharma requested changes

2022-01-26 10:14 UTC, kalpana19sharma commented on sort.rb
> +      end
```suggestion
      tax_rate = is_exempt?(i) ? 0.0 : 0.10
      tax_rate += 0.5 if i.include?('imported')
      obj2.calculate_tax(last, tax_rate) 
```
Will this logic work?

2022-01-26 10:14 UTC, kalpana19sharma commented on tax_determination.rb
> +    bool
```suggestion
    return (product.split & products).present?
```
Will this return the correct value?

2022-01-26 10:14 UTC, kalpana19sharma commented on tax_determination.rb
> +    products = %w(pills book books chocolate chocolates)
Declare this as a constant because this is not going to change.

2022-01-26 10:14 UTC, kalpana19sharma commented on tax_calculate.rb
> +    CalculateTax::WITH_TAX << @value.round(2)
We generally don't modify the value of constants.

2022-01-26 10:14 UTC, kalpana19sharma commented on new_arr.rb
> +      CreateArray::NEW_ARR << temp
Don't modify the constants.

2022-01-26 10:14 UTC, kalpana19sharma commented on new_arr.rb
> +end
Extra white spaces and no new line at the end of the file.

2022-01-26 10:14 UTC, kalpana19sharma commented on new_arr.rb
> +      x = i.split(/ /)
Use meaning full variable names.

2022-01-28 05:45 UTC, kalpana19sharma approved these changes

2022-01-28 05:45 UTC, merged